# Generated by Django 4.2.17 on 2025-01-30 14:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='avatars/default_avatar.png', max_length=255, verbose_name='image'),
        ),
    ]
