# Generated by Django 4.2.17 on 2025-01-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_category_remove_recommendation_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='recommendations', to='recommendations.category'),
        ),
    ]
